//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftStatsdClient open source project
//
// Copyright (c) 2019 the SwiftStatsdClient project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftStatsdClient project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#if !canImport(ObjectiveC)
    import XCTest

    extension StatsdClientTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__StatsdClientTests = [
            ("testCouncurrency", testCouncurrency),
            ("testCounter", testCounter),
            ("testCounterOverflow", testCounterOverflow),
            ("testGaugeDouble", testGaugeDouble),
            ("testGaugeInteger", testGaugeInteger),
            ("testRecorderDouble", testRecorderDouble),
            ("testRecorderInteger", testRecorderInteger),
            ("testTimer", testTimer),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(StatsdClientTests.__allTests__StatsdClientTests),
        ]
    }
#endif
